# Worksheet 04

Name:  Haya AlMajali
UID: U83334432

Partner: Chris Chan

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

d defines the dimensionality of the real space
p is a parameter that you're able to play around with


b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

euclidian distance measures the straight-line distance b/t two points in space
manhattan distance measures the distance b/t two points in space by summing the absolute differences of their coordinates.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

as p becomes really large, the minkowski distance will converge to 1, which is the max difference between any 2 points.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

no, as it no longer meets the criteria to be considered a distance function, and the triangle inequality does not hold (see slides).

e) when would you use cosine similarity over the euclidan distance?

when working with high-dimensional data, where we're looking at similarity based on direction rather than magnitude of vectors.

f) what does the jaccard distance account for that the manhattan distance doesn't?

the jaccard distances cares about whether items are in the sets or not, but not how far apart they are (and this is the opposite for the manhattan distance).

#### Part 2

Consider the following two sentences:

In [54]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [55]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [56]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['name', 'Bob', 'is', 'hello', 'Alice', 'my']
[1, 0, 1, 1, 1, 1]


Let's add a new sentence to our corpus:

In [57]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [58]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['name', 'Bob', 'hi', 'Claude', 'is', 'hello', 'Alice', 'my']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [59]:
v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]

In [60]:
print("Vector representation for s1:", v1)
print("Vector representation for s2:", v2)
print("Vector representation for s3:", v3)

Vector representation for s1: [1, 0, 0, 0, 1, 1, 1, 1]
Vector representation for s2: [1, 1, 0, 0, 1, 1, 0, 1]
Vector representation for s3: [1, 0, 1, 1, 1, 0, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [61]:
import numpy as np

def manhattan_distance(v1, v2):

    if len(v1) != len(v2):
        raise RuntimeError("x & y should be the same dimension")

    v1 = np.array(v1)
    v2 = np.array(v2)
    return np.sum(np.abs(v1 - v2))

print(f"v1 - v2: {manhattan_distance(v1, v2)}")
print(f"v1 - v3: {manhattan_distance(v1, v3)}")
print(f"v2 - v3: {manhattan_distance(v2, v3)}")

v1 - v2: 2
v1 - v3: 4
v2 - v3: 4


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [65]:
import numpy as np 

s4 = "hi Alice"
s5 = "hello Claude"
s6 = "Bob my name is Claude"
s7 = "hi Claude my name is Alice"
s8 = "hello Bob"

corpus = [s1, s2, s3, s4, s5, s6, s7, s8]
all_words = list(set([item for x in corpus for item in x.split()]))

new_vectors = [[1 if x in s1 else 0 for x in all_words] for s in corpus]
matrix = np.array(new_vectors)
print(all_words)
print(matrix)

['name', 'Bob', 'hi', 'Claude', 'is', 'hello', 'Alice', 'my']
[[1 0 0 0 1 1 1 1]
 [1 0 0 0 1 1 1 1]
 [1 0 0 0 1 1 1 1]
 [1 0 0 0 1 1 1 1]
 [1 0 0 0 1 1 1 1]
 [1 0 0 0 1 1 1 1]
 [1 0 0 0 1 1 1 1]
 [1 0 0 0 1 1 1 1]]


e) How many rows and columns does this matrix have?

In [66]:
r, c = np.shape(matrix)
print(f"the matrix has {r} rows and {c} columns")

the matrix has 8 rows and 8 columns


f) When using the Manhattan distance, which two sentences are the most similar?

In [70]:
dist = np.ones((r, r)) * np.inf
for row in range(r):
    for col in range(row + 1, c):
        dist[row, col] = manhattan_distance(matrix[row], matrix[col])

min_dist = np.min(dist)
print(min_dist)
sent1, sent2 = np.nonzero(dist == min_dist)
print(f"The words with the shortest distance is s{sent1[0]} and s{sent2[0]}")

0.0
[0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 4 4 4 5 5 6]
[1 2 3 4 5 6 7 2 3 4 5 6 7 3 4 5 6 7 4 5 6 7 5 6 7 6 7 7]
The words with the shortest distance is s0 and s1


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [78]:
import numpy as np

def compute_distances(graphs):
    graphs = np.array(graphs)
    upper_tri = np.triu(graphs)
    
    num_graphs, vertices, _ = np.shape(graphs)
    exp_graphs = np.expand_dims(upper_tri, axis=0)
    rep_graphs = np.repeat(exp_graphs, num_graphs, axis=0)

    tp_graphs = np.transpose(rep_graphs, axes=(1, 0, 2, 3))
    d_edges = np.not_equal(rep_graphs, tp_graphs)

    distances = np.sum(np.sum(d_edges, axis=3), axis=2)
    print(distances)
    return distances

In [80]:
import numpy as np
import ipytest

def test_compute_distance():
    # Arrange
    input_graphs = [
        np.array([
            [0, 1, 0],
            [1, 0, 0],
            [0, 1, 0]
        ]),
        np.array([
            [0, 1, 1],
            [1, 0, 0],
            [1, 1, 0]
        ]),
        np.array([
            [1, 0, 0],
            [0, 0, 0],
            [0, 0, 0]
        ]),
        np.array([
            [1, 1, 1],
            [1, 0, 0],
            [1, 0, 0]
        ])
    ]
    expected_output = np.array([
        [0, 1, 2, 2],
        [1, 0, 3, 1],
        [2, 3, 0, 2],
        [2, 1, 2, 0],
    ])

    # Act
    computed_distances = compute_distances(input_graphs)

    # Assert
    assert np.all(computed_distances == expected_output)

ipytest.run()

======================================= test session starts ========================================
platform darwin -- Python 3.11.7, pytest-8.0.0, pluggy-1.4.0
rootdir: /Users/hayamaj/cs506/lecture_04
collected 1 item

t_fd17be4d23854e15b08d213c8e2c6f32.py .                                                      [100%]

======================================== 1 passed in 0.01s =========================================


<ExitCode.OK: 0>